[package]
name = "contrasting_colors"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.10.0"
parking_lot = "0.12.3"
itertools = "0.13.0"
rand = "0.8.5"