[package]
name = "contrasting_colors"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.1"
parking_lot = "0.12.1"
itertools = "0.12.1"
rand = "0.8.5"